#GLOBAL CONSTANTS
from os import path

# Game settings.
CAPTION = 'Pong Advanced'
WINDOWWIDTH = 480
WINDOWHEIGHT = 360
BORDERTHICKNESS = 20
CENTRELINETHICKNESS = 4
POINTSFONTSIZE = 36
YPOSPOINTS = 15
XPOSPOINTSP1 = WINDOWWIDTH * 0.75
XPOSPOINTSP2 = WINDOWWIDTH / 4
FPS = 30
IMG_DIR = path.join(path.dirname(__file__), 'image')
SND_DIR = path.join(path.dirname(__file__), 'sound')
ARENAFILE = 'background.png'
CHALLENGEARENAFILE = 'challenge_background.png'
PADDLEFILE = 'paddle.png'
BALLFILE = 'ball.png'

# Sprite Properties.
PADDLEWIDTH = 20
PADDLEOFFSET = 40
BALLSIDE = 20
POWERUPSIZE = 25
# Time is always in milliseconds for all variables.
BARRIERUPTIME = 8000 
OBSTACLEUPTIME = 5000
MINGENERATETIME = 10000
MAXGENERATETIME = 20000
MINSPAWNTIME = 10000
MAXSPAWNTIME = 15000
MISSILEPOSX = -50
BARRIERWIDTH = 20
GOALPOSTWIDTH = 40
GOALPOSTLENGTH = 107
GOALDEPTH = 15
HEALTHBARHEIGHT = 10
HEALTHBARLENGTH = 100

# Define colours.
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
